name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get install mingw-w64 make gcc g++ g++-mingw-w64
        wget https://go.dev/dl/go1.24.4.linux-amd64.tar.gz -O /tmp/go1.24.4.linux-amd64.tar.gz
        sudo rm -rf /usr/local/go /usr/local/bin/go
        sudo tar -C /usr/local -xzf /tmp/go1.24.4.linux-amd64.tar.gz
        sudo ln -s /usr/local/go/bin/go /usr/local/bin/go
        
        git clone https://github.com/Adaptix-Framework/go-win7 /tmp/go-win7
        sudo mv /tmp/go-win7 /usr/lib/
        sudo apt-get install gcc g++ build-essential make cmake mingw-w64 g++-mingw-w64 libssl-dev qt6-base-dev qt6-websockets-dev qt6-declarative-dev

    - name: Build Server
      run: |
        make server
        make extenders

    - name: Build Client
      run: make client

    # === 新增：打包 dist/ 目录 ===
    - name: Archive dist
      run: |
        set -euxo pipefail
        test -d dist
        tar -czf "dist-${{ github.ref_name }}-${{ github.run_number }}.tar.gz" -C dist .

    # === 新增：上传为制品 ===
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ github.ref_name }}-${{ github.run_number }}
        path: dist-${{ github.ref_name }}-${{ github.run_number }}.tar.gz
        if-no-files-found: error
        retention-days: 14
