name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: 
        sudo apt-get install mingw-w64 make gcc g++ g++-mingw-w64
        wget https://go.dev/dl/go1.24.4.linux-amd64.tar.gz -O /tmp/go1.24.4.linux-amd64.tar.gz
        sudo rm -rf /usr/local/go /usr/local/bin/go
        sudo tar -C /usr/local -xzf /tmp/go1.24.4.linux-amd64.tar.gz
        sudo ln -s /usr/local/go/bin/go /usr/local/bin/go
        
        git clone https://github.com/Adaptix-Framework/go-win7 /tmp/go-win7
        sudo mv /tmp/go-win7 /usr/lib/

    - name: Build Server
      run: 
        make server
        make extenders

    - name: Build Client
      run: make client
